// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package google

import (
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/cognitoidentity"
	"github.com/skpr/cognito-auth/pkg/awscreds"
	"github.com/skpr/cognito-auth/pkg/config"
	"github.com/skpr/cognito-auth/pkg/googleauth"
	"github.com/skpr/cognito-auth/pkg/oauth"
)

// Injectors from wire.go:

func InitializeLoginHandler(cacheDir string, cognitoConfig *config.Config, sess *session.Session, awsConfig []*aws.Config) *googleauth.LoginHandler {
	fileCache := oauth.NewFileCache(cacheDir)
	awscredsFileCache := awscreds.NewFileCache(cacheDir)
	tokensRefresher := googleauth.NewTokensRefresher(cognitoConfig, fileCache)
	tokensResolver := oauth.NewTokensResolver(fileCache, tokensRefresher)
	cognitoIdentity := cognitoidentity.New(sess, awsConfig...)
	credentialsResolver := awscreds.NewCredentialsResolver(cognitoConfig, awscredsFileCache, tokensResolver, cognitoIdentity)
	loginHandler := googleauth.NewLoginHandler(cognitoConfig, fileCache, credentialsResolver)
	return loginHandler
}
